interface SearchRecordingQueryArgs extends SearchQueryArgs {
    alias?: string
    arid?: string
    artist?: string
    artistname?: string
    comment?: string
    country?: string
    creditname?: string
    date?: string
    dur?: number
    firstreleasedate?: string
    format?: string
    isrc?: string
    number?: string
    position?: number
    primarytype?: string
    qdur?: number
    recording?: string
    recordingaccent?: string
    reid?: string
    release?: string
    rgid?: string
    rid?: string
    secondarytype?: string
    status?: string
    tag?: string
    tid?: string
    tnum?: number
    tracks?: number
    tracksrelease?: number
    type?: string
    video?: boolean
}